name: Account Memories

on:
  push:
  workflow_dispatch:

jobs:
  account_memories:
    name: Account Memories CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['21.x', '18.x', '17.x']
        flutter-version: ['3.0.5']
    steps:
    - name: コードをチェックアウトする
      uses: actions/checkout@v4
    - name: Java をセットアップする
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
    - name: fvm を準備する
      uses: kuhnroyal/flutter-fvm-config-action@v2
      id: fvm-config-action
    - name: Flutter をセットアップする
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
        channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
    - name: Java, Flutter & Dart のバージョンを確認する
      run: |
        java --version
        flutter --version
        dart --version
    - name: Flutter の依存ライブラリをインストールする
      run: flutter pub get
    - name: Flutter の Lint を実行する
      run: flutter analyze
    - name: Flutter のテストを実行する
      run: flutter test
